Importing the function from the module:V

Testing for module docstring:
    >>> m = __import__("7-base_geometry").__doc__
    >>> len(m) >= 1
    True

Testing for class docstring:
	>>> c = __import__("7-base_geometry").BaseGeometry.__doc__
	>>> len(c) >= 1
	True


Testing for method docstring:
	>>> mod = __import__("7-base_geometry").BaseGeometry.area.__doc__
	>>> len(mod) >= 1
	True

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()

>>> bg.integer_validator("my_int", 12)

>>> bg.integer_validator("name", "John")
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", True)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", 15.6)
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("name", (5,6))
Traceback (most recent call last):
...
TypeError: name must be an integer

>>> bg.integer_validator("cccc", complex(5, 6))
Traceback (most recent call last):
...
TypeError: cccc must be an integer

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("distance", -4)
Traceback (most recent call last):
...
ValueError: distance must be greater than 0

>>> bg.integer_validator("integer")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'


>>> hasattr(bg, '__dict__')
True


>>> type(bg).__name__ == "BaseGeometry"
True

>>> hasattr(bg, "__class__")
True

>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented

>>> bg.area(1)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given

Testing for no arguments to integer_validator:
	 >>> bg.integer_validator()
	 Traceback (most recent call last):
         ...
	 TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Testing for only 1 argument to integer_validator:
	 >>> bg.integer_validator("integer")
	 Traceback (most recent call last):
         ...
	 TypeError: integer_validator() missing 1 required positional argument: 'value'

Testing for too many arguments:
	 >>> bg.integer_validator("integer", 1, 2)
	 Traceback (most recent call last):
         ...
	 TypeError: integer_validator() takes 3 positional arguments but 4 were given
